name: Build and deploy ASP.Net Core app to Azure Web App - esay-recipe-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Set the appropriate version

      - name: Build the app
        run: |
          cd C#-backend
          dotnet restore
          dotnet build --configuration Release

